site_name: DocEngine
site_description: AI-assisted technical documentation
site_author: Maryam Rehman

docs_dir: docs
site_dir: site
use_directory_urls: true

nav:
  - Home: index.md

  - User Guide:
      - Register a Patient: UserGuide/Register a patient.md
      - Book an Appointment: UserGuide/book-appointment.md
      - Quick Start: UserGuide/quickstart.md

  - API Reference:
      - OpenAPI: api/openapi.md

  - Release Notes:
      - Version 1.0.0: release-notes/v1.0.0.md
      - Version 1.0.1: release-notes/v1.0.1.md

  - Glossary: glossary.md

  - Style Guide: style-guide.md

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

copyright: © 2026 DocEngine